# Generated by Django 2.0 on 2020-03-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('geo', '0001_initial'),
        ('supply', '0004_supplier_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Position', verbose_name='Адрес')),
                ('product', models.ManyToManyField(to='products.Product', verbose_name='Продукт')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.Supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Точка продаж',
                'verbose_name_plural': 'Точки продаж',
            },
        ),
    ]
