# Generated by Django 2.0 on 2020-03-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование продукта')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Описание продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование группы')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа продуктов',
                'verbose_name_plural': 'Группы продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductGroup', verbose_name='Продуктовая группа'),
        ),
    ]
